#trigger_job:
#    trigger:
#      include: child-pipeline.yml

# Difference in trigger_jon and include is that with include it acts as single job now
include:
    - local: 'child-pipeline.yml'
    
default:
    timeout: 1 hour
    


stages:
    - precheck
    #- build
    #- test
    #- deploy

CI_Pre_Check:
    stage: pre-check
    tags:
        - CI
        - Devops
    only:
        - main
    #parallel: 2
    
CI_Build:
    stage: build
    tags:
        - CI
        - Devops
    needs: []
    retry: 2
    inherit:
        default: false
    only:
        - main
    before_script:
        - echo "Build Started"
        - sleep 10
    script:
        - sudo dockr build -t $Image_Name:$CI_PIPELINE_IID .
    after_script:
        - sudo docker images
    cache:
        key: "mycache"
        paths:
            - ./
    artifacts:
        name: "devops"
        when: on_failure
        paths:
           - ./
        expire_in: 1 week
        exclude:
           - .gitlab-ci.yml
